### ISSUE TITLE
Chest randomly disappear

### ISSUE THREAD

**Issue by cupang-afk** [DevCyntrix/death-chest#25]
while testing this bug #24
my friend somehow find his death chest was disappeared

he says quoted "i just death and opened the chest, and it disappeared"

fortunately hologram is enabled in the config, and it create this behaviour
![image](https://user-images.githubusercontent.com/66926348/210125842-65d53e08-ccb3-47a6-bab0-6b71f2cc30e4.png)

a note:
i cant reproduce this bug im sorry

**Comment by DevCyntrix** [comment]
Are you using the newest version or do you have an exception in the console?

**Comment by DevCyntrix** [comment]
That is weird because it chest only disappear if the chest has no items stored

**Comment by cupang-afk** [comment]
yes i have version 1.5.14 installed
and this only happen once *(the time when my friend testing the dupe bug)*

for about many times trying to replicate this bug, it seem i cant produce the same behaviour like this one

**Comment by DevCyntrix** [comment]
Ok but for now I recommend to update the plugin to the newest version because it is very difficult to support older plugin versions.
