### ISSUE TITLE
Bug with multiblock structures

### ISSUE THREAD

**Issue by cupang-afk** [DevCyntrix/death-chest#27]
Bug explain:
if you died on top of a bed or door
it will change one of the block that you standing and drop the block

if you break/take item from the deathchest 
the deathchest is gone and it create this bizzare screenshot
![image](https://user-images.githubusercontent.com/66926348/211180228-49085ea8-02a0-4be3-ad89-9a2628e96e5d.png)

also for scaffolding 
if you are for example died at the very bottom of scaffolding 
it will break the entire scaffolding connected to it (posible to happen with twisting vine)

if you died at the middle, this happen (break the bottom scaffolding before take the deathchest)
![image](https://user-images.githubusercontent.com/66926348/211180590-58292089-5f6d-4f7d-ae38-301827f0d8f8.png)

im fine with bed and door, but for the scaffolding is sometime annoy me (because i have scaffolding near a wall, and often hitting the wall while flying with elytra, im dumb dumb)

**Comment by DevCyntrix** [comment]
Thank you very much, I will fix it soon! 😄

**Comment by DevCyntrix** [comment]
Which version did you use?

**Comment by cupang-afk** [comment]
its the latest 1.5.16 version

**Comment by DevCyntrix** [comment]
It will be fixed in the next version :D Thank you very much for your report!
