### ISSUE TITLE
Death on top of a chest doesn't put DeathChest on top of a chest

### ISSUE THREAD

**Issue by cupang-afk** [DevCyntrix/death-chest#28]
hello its me again :)

as you guess, i died on top of a chest
but the death chest is spawned a bit far from the chest
![image](https://user-images.githubusercontent.com/66926348/218322276-318a4762-4690-4e7c-aab9-bebf3fb6c6ba.png)

my user were reporting that they died near the edge on an end island, on top of a chest
and the death chest is spawned flying in the void _(a bit far from the death location, more likely 10+ blocks)_ _(i saw the evidence, but i forgot to take a screenshot)_

expected behavior:
death chest is spawned on the exact death location of the player, in this case is on top of a chest

additional note:
- DeathChest version `1.5.17`
- i also tried on a single chest block

**Comment by cupang-afk** [comment]
New find

i've tried on a couple of block
- soul sand
- mud
- farmland

this also shown the same behaviour _(death chest not spawned on top of the block)_

if you place those block equal to the ground, the death chest has nowhere to be found _(i think the death chest is searching nearest location with equal y level with air block in it a.k.a free space, but i haven't find mine yet T-T)_

**Comment by DevCyntrix** [comment]
Hi, thank you very much for the report. Yes, this is because the block are not full blocks. Relative to the location your are "in" the block. To avoid block replacement and bugs with multiblocks I added a "algorithm" which is looking for the next block which isn't solid. I will looking for a solution :)
