### ISSUE TITLE
Massive Server Lag on hoppers.

### ISSUE THREAD

**Issue by darealblack** [DevCyntrix/death-chest#29]
Spark:
![image](https://user-images.githubusercontent.com/79378716/219966125-61d11605-af27-4958-bdbc-6fcbfe4b705b.png)

In the server we are using hoppers, when hoppers are used in farms the server lags to 7-10 tps? Why does this take so much tps?
Im currently using 1.5.8 I I will update if this continues in 1.5.17!

**Comment by darealblack** [comment]
Seems to be working. Not sure though. Server at stable 20 frames. I will check after 12 hours how the server is running with spark

**Comment by DevCyntrix** [comment]
Hi,
this bug should be fixed in the newest version 🙂

**Comment by darealblack** [comment]
Alright Issue Fixed, after 12 hours of using spark profiler it works. Server tps at stable 20 tps thanks
