### ISSUE TITLE
GriefPrevention support

### ISSUE THREAD

**Issue by TheJoshue** [DevCyntrix/death-chest#4]
Hello
this plugin is good plugin for survival game type

a lot of survival servers use plugin GriefPrevention

if you can only allow player's death chest to be spawned ONLY and ONLY if: player is in nobody's protected region OR is in his own region (and maybe, think of adding support for plugin Parties too because GriefPrevention don't have team system but using Parties plugin you can create one as each other support themselves, so you can check if player who died is either in: `1`. nobody's region (wild); `2`. his own region; `3`. in region from player who is in the same party like him)

thank you so much.

**Comment by DevCyntrix** [comment]
Could you send me the website where you downloaded GriefPrevention, because have found more than one plugin.

**Comment by TheJoshue** [comment]
1.18-1.18.2 .jar:
https://dev.bukkit.org/projects/grief-prevention/files/3668748/download

1.16.X .jar:
https://dev.bukkit.org/projects/grief-prevention/files/3173411/download

if you could please make sure that it works with both jars (if you can, if not, at least with latest one, it will probably work with 1.16 one too)

**Comment by DevCyntrix** [comment]
Now the plugin should support GriefPrevention. If something went wrong, please contact me.
