### ISSUE TITLE
QUESTION - How can I display a world "Alias" in place of the world "Name" when using Placeholders?

### ISSUE THREAD

**Issue by level42ca** [DevCyntrix/death-chest#49]
I'm looking to customize the Placeholder of DeathChests, by having it show the world "Alias" in lieu of the world "Name", but I haven't been able to figure out how to do this, or if this is even possible.

I've tried a few alternatives in the PAPI Config.yml file, such as `<worldname>` and `<worldalias>` etc, to no avail. I've even attempted embedding another placeholder in here, which also doesn't render properly: `%multiverse_world_name_colored%`

I have a multiverse set up with like 10 different worlds, but my players only know of the worlds by their Alias names, thus it's important to me to display where their previous death chest is, by the Alias.

Example:
![image](https://github.com/DevCyntrix/death-chest/assets/12260575/0dccaa4e-e737-435f-be3e-452d291e9fc2)
![image](https://github.com/DevCyntrix/death-chest/assets/12260575/586b8405-e4bb-4c18-8d6d-c04259e3a07c)

**Comment by level42ca** [comment]
Any ideas?

**Comment by level42ca** [comment]
Just checking in to see if there's any advice here.

**Comment by DevCyntrix** [comment]
I have no idea how I could support this. Do you use placeholder API?

**Comment by level42ca** [comment]
So, I actually managed to figure out my own solution, using the "ChageOutput" placeholder.

Essentially, I check for what the DeathChest placeholder outputs, and if it matches the world string "World-Main-Survival-120" then replace it with the pretty name "PowderHill".

But I appreciate your response none the less :)

**Comment by DevCyntrix** [comment]
Nice to know!
