### ISSUE TITLE
Persistent chests (server reload/restart)

### ISSUE THREAD

**Issue by TBG-FR** [DevCyntrix/death-chest#6]
Hello there ! Good job on that awesome plugin, which seems to work really well 👌 

I've seen the following lines in the config
```
# The expiration of the chest in seconds.
# You can deactivate the expiration by setting the value to -1,
#  but warning: The chest will still disappear after a server reload/restart
```

And I was wondering if we could find a way to avoid loosing a player's stuff if the server is reloaded/restarted ? Is it planned ? Do you have any ideas ? I believe it means that the plugin should be able to create a file (or a database, but that's heavier of course), to store the data ?

I'll be honest, I didn't check the source code for now to see how you store the chest inventory, but I'll do it ! 

Thanks in advance for your answer 😉

**Comment by DevCyntrix** [comment]
Hello,
persistent chests should already work. I just forgot to remove the description in the configuration.

**Comment by TBG-FR** [comment]
You're right, I just tried it, and it works ! Sorry for the issue, I've paid attention only to the config file, without testing or reading the releases 😅
