### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by KikyoC** [DevCyntrix/death-chest#91]
**Describe the bug**
Plugin not loading
**To Reproduce**
Minecraft Server Implementation: Spigot, Paper, Purpur, Pufferfish
Paper 1.21.1
Just install the plugin on the server

This is caused by a bad relocation of metrics when the plugin is enabling (I don't have fix for that bug)

**Comment by DevCyntrix** [comment]
Hey @KikyoC ,
did you try to build the plugin by your own? If so, you need to build the plugin with the gradle shadow command.

Best reguards
